-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgjqydi0cIKg4fhEjo
m/vYjYnM6tjou8cE+Ifu4Ibad/SgCgYIKoZIzj0DAQehRANCAARClSY1GG3xysMz
1MWO9xsKUmJKKgkyoa4PZiz8eXJKEXMjIiqwV33z7QPPx1ENax9P8tW6KUMuShEE
3DOlbwp3
-----END PRIVATE KEY-----